POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Test event 2",
  "description": "A second test event",
  "location": " A second test location",
  "dateTime": "2025-12-24T15:23:43+07:00"
}